### ISSUE TITLE
Theme breaking on Visual Studio

### ISSUE THREAD

**Issue by anime-shed** [johnyenter-briars/gruvbox-material-vs#13]
Visual Studio version: Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview (Version 17.9.0 Preview 1.0)

Issue:

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/9a9d4b01-33da-4cf3-bd8f-49efa01edc3d)
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/f3ce8215-7a6c-4f6d-b7b2-fcfeb5a45268)
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/16bd212d-8414-4ab7-bc29-8d402b7fd6ce)

I loved this theme, but after some recent updates, this is not working for me. I hope this can be fixed and I can continue to enjoy it.

**Comment by johnyenter-briars** [comment]
Hey @anime-shed thank you for finding value in the tool and using it! 

I tried to replicate this issue, but installing the extension on VS Community and VS Enterprise (preview) but was unable to.  

## Visual Studio Community Preview
![working_vs_community_2022_preview](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/cbea1f8d-35b3-446a-a8b2-a694eeca09c7)
![working_vs_community_2022_preview_version](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/d903b4f8-ca87-4f19-99a0-15948fa07989)

## Visual Studio Enterprise Preview
![working_vs_enterprise_2022_preview](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/f5e82f9a-a17d-42fb-aeb4-549f8b3f609a)
![working_vs_enterprise_2022_preview_version](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/3df445da-5706-4d9d-a7e0-9d2d6d409a46)

Could you check what version of the extension you have installed? If it's 0.6.0, could you try reinstalling the extension to see if that solves the problem?

You can also make sure the extension gets cleared away by making sure the extension `pkgdef` file is truly deleted while reinstalling by [deleting the folder directly](https://learn.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2022#per-user-and-administrative-extensions).

**Comment by anime-shed** [comment]
Hi @johnyenter-briars, I tried to reinstall it after verifying that the `pkgdef` file is truly deleted and it still does not work.
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/8ffdbe2d-b61a-4c16-a6f3-6702378b615f)


Sorry for not sharing the detailed info about the VS version:
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/3b7e940a-2e24-41ae-a104-c2114031f22e)

__**Seems like I found the culprit:**__
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/cc41714d-7c41-410b-848f-09586cfd221b)
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/a0922b6d-f2fd-4191-a546-e6d342b31b14)

Since this was working with the alternate theme I was using, I thought this might be backwards compatible with this theme too. But seems like it is not, can you try to see what might be breaking cause for the same.

**Comment by johnyenter-briars** [comment]
@anime-shed, ok yea I can replicate the issue now. It looks like the editor works, but the window pane doesn't. I suspect this has to do with the new ability to 'tint' the surrounding [window pane.](https://devblogs.microsoft.com/visualstudio/the-visual-studio-ui-refresh-preview-is-here/) 

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/87509e0a-abb9-404b-b5fd-fb70b04af45a)

The gruvbox-material-vs theme was origionally ported from an older "VS Theme project" for 2019, and then I rebuilt it using [Visual Studio Color Theme Designer 2022](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022). So I suspect the XML property for "window pane" has changed with the new "UI Refresh".

I'll check it out and see if I can find that new property - I can't guarantee when I'll be able to get it fixed though - but I'll do my best : )

In the meantime - what vs theme / extension are you using that *does* work in the new "UI Refresh"?

**Comment by anime-shed** [comment]
@johnyenter-briars I will be glad if this is fixed.
The vs extension I was talking about:
https://github.com/jekelly/gruvboxvs
https://marketplace.visualstudio.com/items?itemName=jeffkelly.gruvboxvs10

**Comment by johnyenter-briars** [comment]
@anime-shed Haha - I know that theme well. The fact that it wasn't *quite* what I was looking for was what inspired me to make / publish this theme : )

So it looks like with the "UI Refresh" the categories that control those colors are:

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/2238223a-39be-4641-99e0-e7b768124fab)

I'm not sure what use they serve in VS 2022 non preview. 

I was able to make some progress, if you're curious you can preview the changes / build / test the extension for yourself at branch: #14

**Comment by johnyenter-briars** [comment]
@anime-shed  Ok, did some work on the theme - I'm not a UI designer by any means, but I tried to use different grey colors to maintain the visual feeling of 'layers' on the new UI buttons.

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/d19008d8-f68e-4406-8653-2fead5cb0821)


You wanna take a look at #14 when you get a chance? You should be able to check out that branch, and then do a local build / install in your VS 2022 Preview instance. 

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/c2067635-2612-4326-a7e5-2a2128506737)


I'll do the same, and use it for the next week locally before I publish - just to see if there are any fixes needed.

**Comment by anime-shed** [comment]
Hi, I tried to build/run locally but for some reason I am not able to load the project
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/d49af215-fe9e-40c6-8717-27c1dece2b32)

**Comment by johnyenter-briars** [comment]
@anime-shed do you have the VS theme extension I kinked above?

**Comment by anime-shed** [comment]
Edit:

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/f7ea05ed-94c0-49b3-a91d-060efd8d68af)

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/c3e85941-236a-40f5-a8ca-5484c0b22525)

This is all I can see.

**Comment by anime-shed** [comment]
I was able to build it after editing:
https://github.com/johnyenter-briars/gruvbox-material-vs/blob/master/gruvbox-material-vs/gruvbox-material-vs.csproj#L76

```
 <Import Project="$(VSToolsPath)\VSSDK\Microsoft.VsSDK.targets" />
```

**Comment by johnyenter-briars** [comment]
Hmm - not sure why removing the `Condition="'$(VSToolsPath)' != ''"` would change anything - that looks like valid templating to me. And it looks like it's upset about 'A character in the path' - strange. But glad you got it working!

**Comment by anime-shed** [comment]
I tried using it, but some colour schemes make text less visible. This will be an extensive list, so will be updating it in the same:

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/7c592eae-772f-4724-83ce-9d3eb28263d2)

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/2749bd54-f38d-4324-91d7-68e025cdba1d)
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/67512697/c1ae7f0a-ab85-4582-bdb4-fe4df4ca8c2a)

**Comment by johnyenter-briars** [comment]
@anime-shed  Ok right on! Since that seems like an enhancement to me - as opposed to a bug fix (or in this case supporting the preview VS version) - can you open a new issue for that? (Or maybe even a PR if you see fit? ;) ) 

I'd like to close this issue and #14  for now and get this out on the marketplace : )
