### ISSUE TITLE
[Request] Color for c/c++ files

### ISSUE THREAD

**Issue by rocascent** [johnyenter-briars/gruvbox-material-vs#17]

**Comment by johnyenter-briars** [comment]
@Gn3po4g  - thank you for your interest in this extension!

I can work on implementing this feature for you. One thing though - I'm not a c++ programmer, so my knowledge about the language is a bit hazy. 

Would you be open to working with me on it as I make additions / changes?

All you would need to do would be run a local build of the extension and install it on your local VS instance to test it as I make changes.

I've started work here: #18 . 

Thanks!

Edit: I only plan to support this for the theme `gruvbox-material-dark-custom`. The theme: `gruvbox-material-dark` was an automatic port of a preivous theme - and I havn't done any customizations on that one. So I'm leaving that one as is.

**Comment by rocascent** [comment]
C++ is similar to C#, so just the same as C# highlighting you designed is okay.

**Comment by johnyenter-briars** [comment]
@Gn3po4g  ok - I'll do my best but I only want to push to the VS market place **once**. Does that make sense?

I don't want to go back and forth where I publish it - then we realize that it's missing some obscure c++ syntax highlighting. Like I publish and it's missing "template highlighting" for example. 

So I'll let you know when I've gotten it as good as I got - and then you can run a local build and install it and confirm it it suits your needs - does that sound ok? 

For reference - here's where I got to today on #18 

![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/14f32a2a-fd2b-4247-8abe-f594515c8aa8)
![image](https://github.com/johnyenter-briars/gruvbox-material-vs/assets/42982326/e254a7b8-0316-434c-ab84-6aa2a4993526)

**Comment by rocascent** [comment]
No problem, I can provide some test code.
```cpp
template <typename T>
concept displayable = requires(T t) {
    t.display();
};

// Template function
template <displayable T>
void printVector(const std::vector<T>& vec) {
    for (const auto& item : vec) {
        item.display();
    }
}

constexpr size_t operator""_len(const char *str, size_t size) { return size; }

size_t len = "string"_len;
```
If I think of others, I'll add them here.

**Comment by johnyenter-briars** [comment]
@Gn3po4g  If you think of others please add them to [this file](https://github.com/johnyenter-briars/gruvbox-material-vs/blob/a96c3f97d34721ff5a1ed9bab58f99d39b90e56b/testFiles/test.cpp)

(You can branch off of my branch)

**Comment by johnyenter-briars** [comment]
@Gn3po4g I'm rapidly loosing time to work on this - but I think I got this in a mostly working state:

![image](https://github.com/user-attachments/assets/705b2f48-7982-44b9-99e0-b92a4929fa90)

I'm going to merge in #18  and close out this issue. 

The updated extension should be on the VS marketplace shortly
