### ISSUE TITLE
Lost style `StickyScroll Background`

### ISSUE THREAD

**Issue by rocascent** [johnyenter-briars/gruvbox-material-vs#22]
https://github.com/johnyenter-briars/gruvbox-material-vs/blob/0ded1b397129b62ccc8e2fae5673b00a3397f7d6/gruvbox-material-vs/gruvbox-material-dark-custom.vstheme#L7740-L7743

I think it can be set to rgb(50,48,47)

![image](https://github.com/user-attachments/assets/0a2d31f8-c1c0-4796-abe3-637f1daf623d)

**Comment by johnyenter-briars** [comment]
@Gn3po4g  - thanks for this suggestion! 

Feel free to open a PR - and I run run a local build and test - and if it works - I can push it to the vs extension store : )
